# Generated by Django 3.2 on 2020-06-10 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('card_color', models.CharField(max_length=10)),
                ('card_set', models.CharField(max_length=25)),
                ('card_description', models.TextField()),
                ('card_flavor', models.TextField()),
                ('card_artist', models.CharField(max_length=25)),
                ('card_year', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='time')),
                ('listing_price', models.CharField(max_length=6)),
                ('listing_card', models.ManyToManyField(to='main.Card')),
                ('listing_vendor', models.ManyToManyField(to='main.Vendor')),
            ],
            options={
                'ordering': ['listing_price'],
            },
        ),
    ]
