# Generated by Django 3.2 on 2020-07-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200729_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_updated',
            field=models.CharField(default='2020-07-30T03:02:41.320517', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_updated',
            field=models.CharField(default='2020-07-30T03:02:41.322790', max_length=200),
        ),
    ]
